/** Vehicle make options (value + label) for Sell My Car valuation form. */
export const SELL_MY_CAR_MAKES = [
  { value: "abarth", label: "Abarth" },
  { value: "aion", label: "Aion" },
  { value: "alfa-romeo", label: "Alfa Romeo" },
  { value: "alpina", label: "Alpina" },
  { value: "alpine", label: "Alpine" },
  { value: "armstrong-siddeley", label: "Armstrong Siddeley" },
  { value: "asia-motors", label: "Asia Motors" },
  { value: "aston-martin", label: "Aston Martin" },
  { value: "audi", label: "Audi" },
  { value: "austin", label: "Austin" },
  { value: "austin-healey", label: "Austin Healey" },
  { value: "australian-classic-car", label: "Australian Classic Car" },
  { value: "bedford", label: "Bedford" },
  { value: "bentley", label: "Bentley" },
  { value: "bertone", label: "Bertone" },
  { value: "blade", label: "Blade" },
  { value: "bmc", label: "BMC" },
  { value: "bmw", label: "BMW" },
  { value: "bolwell", label: "Bolwell" },
  { value: "bufori", label: "Bufori" },
  { value: "bugatti", label: "Bugatti" },
  { value: "buick", label: "Buick" },
  { value: "byd", label: "BYD" },
  { value: "cadillac", label: "Cadillac" },
  { value: "caterham", label: "Caterham" },
  { value: "chery", label: "Chery" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "chrysler", label: "Chrysler" },
  { value: "citroen", label: "Citroen" },
  { value: "commer", label: "Commer" },
  { value: "csv", label: "CSV" },
  { value: "cupra", label: "CUPRA" },
  { value: "daewoo", label: "Daewoo" },
  { value: "daihatsu", label: "Daihatsu" },
  { value: "daimler", label: "Daimler" },
  { value: "datsun", label: "Datsun" },
  { value: "deepal", label: "Deepal" },
  { value: "denza", label: "DENZA" },
  { value: "de-tomaso", label: "De Tomaso" },
  { value: "dodge", label: "Dodge" },
  { value: "elfin", label: "Elfin" },
  { value: "eunos", label: "Eunos" },
  { value: "farizon", label: "Farizon" },
  { value: "ferrari", label: "Ferrari" },
  { value: "fiat", label: "Fiat" },
  { value: "ford", label: "Ford" },
  { value: "ford-performance-vehicles", label: "Ford Performance Vehicles" },
  { value: "foton", label: "Foton" },
  { value: "fsm", label: "FSM" },
  { value: "gac", label: "GAC" },
  { value: "geely", label: "Geely" },
  { value: "genesis", label: "Genesis" },
  { value: "giocattolo", label: "Giocattolo" },
  { value: "gmc", label: "GMC" },
  { value: "great-wall", label: "Great Wall" },
  { value: "gwm-haval", label: "GWM" },
  { value: "haval", label: "Haval" },
  { value: "hdt", label: "HDT" },
  { value: "hillman", label: "Hillman" },
  { value: "hino", label: "Hino" },
  { value: "holden", label: "Holden" },
  { value: "holden-special-vehicles", label: "Holden Special Vehicles" },
  { value: "honda", label: "Honda" },
  { value: "humber", label: "Humber" },
  { value: "hummer", label: "Hummer" },
  { value: "hyundai", label: "Hyundai" },
  { value: "ineos", label: "INEOS" },
  { value: "infiniti", label: "INFINITI" },
  { value: "international", label: "International" },
  { value: "iso", label: "ISO" },
  { value: "isuzu", label: "Isuzu" },
  { value: "jac", label: "JAC" },
  { value: "jaecoo", label: "Jaecoo" },
  { value: "jaguar", label: "Jaguar" },
  { value: "jeep", label: "Jeep" },
  { value: "jensen", label: "Jensen" },
  { value: "jmc", label: "JMC" },
  { value: "kgm", label: "KGM" },
  { value: "kgm-ssangyong", label: "KGM SsangYong" },
  { value: "kia", label: "Kia" },
  { value: "ktm", label: "KTM" },
  { value: "lada", label: "Lada" },
  { value: "lamborghini", label: "Lamborghini" },
  { value: "lancia", label: "Lancia" },
  { value: "land-rover", label: "Land Rover" },
  { value: "ldv", label: "LDV" },
  { value: "leapmotor", label: "Leapmotor" },
  { value: "lexus", label: "Lexus" },
  { value: "leyland", label: "Leyland" },
  { value: "lightburn", label: "Lightburn" },
  { value: "lincoln", label: "Lincoln" },
  { value: "lotus", label: "Lotus" },
  { value: "mahindra", label: "Mahindra" },
  { value: "maserati", label: "Maserati" },
  { value: "maybach", label: "Maybach" },
  { value: "mazda", label: "Mazda" },
  { value: "mclaren", label: "McLaren" },
  { value: "mercedes-benz", label: "Mercedes-Benz" },
  { value: "mg", label: "MG" },
  { value: "mini", label: "MINI" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "morgan", label: "Morgan" },
  { value: "morris", label: "Morris" },
  { value: "nissan", label: "Nissan" },
  { value: "noble", label: "Noble" },
  { value: "nsu", label: "NSU" },
  { value: "omoda", label: "Omoda" },
  { value: "opel", label: "Opel" },
  { value: "pagani", label: "Pagani" },
  { value: "peugeot", label: "Peugeot" },
  { value: "polestar", label: "Polestar" },
  { value: "pontiac", label: "Pontiac" },
  { value: "porsche", label: "Porsche" },
  { value: "proton", label: "Proton" },
  { value: "ram", label: "RAM" },
  { value: "rambler", label: "Rambler" },
  { value: "renault", label: "Renault" },
  { value: "robnell", label: "Robnell" },
  { value: "rolls-royce", label: "Rolls-Royce" },
  { value: "rover", label: "Rover" },
  { value: "saab", label: "Saab" },
  { value: "seat", label: "Seat" },
  { value: "simca", label: "Simca" },
  { value: "skoda", label: "SKODA" },
  { value: "skywell", label: "Skywell" },
  { value: "smart", label: "smart" },
  { value: "ssangyong", label: "SsangYong" },
  { value: "studebaker", label: "Studebaker" },
  { value: "subaru", label: "Subaru" },
  { value: "suzuki", label: "Suzuki" },
  { value: "tata", label: "Tata" },
  { value: "td-2000", label: "TD 2000" },
  { value: "tesla", label: "Tesla" },
  { value: "toyota", label: "Toyota" },
  { value: "trd", label: "TRD" },
  { value: "triumph", label: "Triumph" },
  { value: "tvr", label: "TVR" },
  { value: "vanden-plas", label: "Vanden Plas" },
  { value: "vauxhall", label: "Vauxhall" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "volvo", label: "Volvo" },
  { value: "wolseley", label: "Wolseley" },
  { value: "xpeng", label: "XPeng" },
  { value: "zeekr", label: "Zeekr" },
  { value: "zx-auto", label: "ZX Auto" },
] as const;

export function sellMyCarMakeLabel(value: string): string {
  const row = SELL_MY_CAR_MAKES.find((m) => m.value === value);
  return row?.label ?? value;
}
